variable "vpc_cidr" {}
variable "vpc_name" {}
variable "IGW" {}
variable "Public_Subnet1_cidr" {}
variable "Public_Subnet2_cidr" {}
variable "az1" {}
variable "az2" {}
variable "Public_Subnet1_name" {}
variable "Public_Subnet2_name" {}
variable "Private_Subnet1_cidr" {}
variable "Private_Subnet2_cidr" {}
variable "Private_Subnet1_name" {}
variable "Private_Subnet2_name" {}
variable "Public_Route_Name" {}
variable "Private_Route_Name" {}
variable "Public_Subnet3_name" {}
variable "Public_Subnet3_cidr" {}
